apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnosy-backend
  namespace: diagnosy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diagnosy-backend
  template:
    metadata:
      labels:
        app: diagnosy-backend
    spec:
      containers:
        - name: diagnosy-backend
          image: asia-docker.pkg.dev/multi-cloud-app-413619/gcr-asia-repo/diagnosy/api:1.0.0
          ports:
            - containerPort: 3001
          imagePullPolicy: Always
