apiVersion: v1
kind: Service
metadata:
  name: diagnosy-api
  namespace: diagnosy
spec:
  selector:
    app: diagnosy-backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
