apiVersion: v1
kind: Service
metadata:
  name: diagnosy-webapp
  namespace: diagnosy
spec:
  selector:
    app: diagnosy-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
