apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: diagnosy
spec:
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      protocol: TCP
  selector:
      app: mongo-express
  type: LoadBalancer
