apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "mongodb-deployment"
  namespace: "diagnosy"
  labels:
      app: "mongodb"
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: "mongodb"
  template:
    metadata:
      labels:
        app: "mongodb"
    spec:
      containers:
        -
          name: "mongodb"
          image: "mongo"
          imagePullPolicy: "Always"
          env:
            -
              name: "MONGO_INITDB_ROOT_USERNAME"
              value: "root"

            -
              name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "r1ty11v32fcs24dsa"

          ports:
            - containerPort: 27017

          volumeMounts:
            -
              name: "mongodb-persistent-storage"
              mountPath: "/data/db"

      volumes:
        -
          name: "mongodb-persistent-storage"
          persistentVolumeClaim:
            claimName: "mongodb-pvc"