apiVersion: v1
kind: Service
metadata:
  name: diagnosy-nginx
  namespace: diagnosy
spec:
    selector:
        app: diagnosy-nginx
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
    type: LoadBalancer
