apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: diagnosy
data:
  nginx.conf: |
    events {
      worker_connections  4096;  ## Default: 1024
    }
    
    http {
        log_format   main '$remote_addr - $remote_user [$time_local]  $status '
            '"$request" $body_bytes_sent "$http_referer" '
            '"$http_user_agent" "$http_x_forwarded_for"';
        access_log   logs/access.log  main;
    
        upstream diagnosy-webapp {
            server diagnosy-webapp:3000;
        }
    
        upstream diagnosy-api {
            server diagnosy-api:3001;
        }
    
        server {
            listen       80;
            server_name  localhost;
            location / {
                proxy_pass diagnosy-webapp;
            }
    
            location /api {
                proxy_pass diagnosy-api;
            }
        }
    }
---